### ISSUE TITLE
模拟器能能跑起来,真机进入登录界面闪崩

### ISSUE THREAD

**Issue by Jeffery336699** [sealtalk/sealtalk-android#12]
`12-30 17:31:20.885 30223-30354/cn.rongcloud.im E/RongLog: [ RongExceptionHandler ] uncaughtException
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/meizu/cloud/pushsdk/PushManager;
        at io.rong.push.core.PushRegistrationService.onHandleWork(PushRegistrationService.java:107)
        at io.rong.imlib.RongJobIntentService$CommandProcessor.doInBackground(RongJobIntentService.java:405)
        at io.rong.imlib.RongJobIntentService$CommandProcessor.doInBackground(RongJobIntentService.java:389)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.meizu.cloud.pushsdk.PushManager" on path: DexPathList[[zip file "/data/app/cn.rongcloud.im-2/base.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_dependencies_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_0_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_1_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_2_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_3_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_4_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_5_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_6_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_7_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_8_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/cn.rongcloud.im-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at io.rong.push.core.PushRegistrationService.onHandleWork(PushRegistrationService.java:107) 
        at io.rong.imlib.RongJobIntentService$CommandProcessor.doInBackground(RongJobIntentService.java:405) 
        at io.rong.imlib.RongJobIntentService$CommandProcessor.doInBackground(RongJobIntentService.java:389) 
        at android.os.AsyncTask$2.call(AsyncTask.java:292) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: com.meizu.cloud.pushsdk.PushManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 9 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
12-30 17:31:22.320 4945-20846/? E/NativeCrypto: ssl=0xeec43800 cert_verify_callback x509_store_ctx=0xdc36d5e0 arg=0x0
12-30 17:31:22.320 4945-20846/? E/NativeCrypto: ssl=0xeec43800 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
12-30 17:31:22.417 4945-20846/? E/SubmitUtil: submit onError:HTTP 401 Unauthorized
12-30 17:31:33.530 30373-30434/cn.rongcloud.im E/NativeCrypto: ssl=0xf4888c00 cert_verify_callback x509_store_ctx=0xdf688c40 arg=0x0
12-30 17:31:33.531 30373-30434/cn.rongcloud.im E/NativeCrypto: ssl=0xf4888c00 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
12-30 17:31:33.535 30373-30437/cn.rongcloud.im E/NativeCrypto: ssl=0xeec3fc00 cert_verify_callback x509_store_ctx=0xdf462b40 arg=0x0
12-30 17:31:33.536 30373-30437/cn.rongcloud.im E/NativeCrypto: ssl=0xeec3fc00 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
12-30 17:31:33.617 30373-30445/cn.rongcloud.im E/RongLog: [ RongExceptionHandler ] uncaughtException
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/meizu/cloud/pushsdk/PushManager;
        at io.rong.push.core.PushRegistrationService.onHandleWork(PushRegistrationService.java:107)
        at io.rong.imlib.RongJobIntentService$CommandProcessor.doInBackground(RongJobIntentService.java:405)
        at io.rong.imlib.RongJobIntentService$CommandProcessor.doInBackground(RongJobIntentService.java:389)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.meizu.cloud.pushsdk.PushManager" on path: DexPathList[[zip file "/data/app/cn.rongcloud.im-2/base.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_dependencies_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_0_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_1_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_2_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_3_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_4_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_5_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_6_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_7_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_8_apk.apk", zip file "/data/app/cn.rongcloud.im-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/cn.rongcloud.im-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at io.rong.push.core.PushRegistrationService.onHandleWork(PushRegistrationService.java:107) 
        at io.rong.imlib.RongJobIntentService$CommandProcessor.doInBackground(RongJobIntentService.java:405) 
        at io.rong.imlib.RongJobIntentService$CommandProcessor.doInBackground(RongJobIntentService.java:389) 
        at android.os.AsyncTask$2.call(AsyncTask.java:292) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: com.meizu.cloud.pushsdk.PushManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 9 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available`

截取了报错信息,我用的是魅族mx5,还要一个魅族16th,都是闪崩

**Comment by JennyZhou918** [comment]
没有复现这个问题。是用源码直接跑的吗？是否有修改？另外在同样手机上试试最新版本还能复现吗？
