### ISSUE TITLE
versionCode 2019022217  这个版本登录按钮点击崩溃

### ISSUE THREAD

**Issue by leielyq** [sealtalk/sealtalk-android#18]

**Comment by leielyq** [comment]
2019-02-26 09:29:49.717 4942-4942/cn.rongcloud.im:ipc E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.rongcloud.im:ipc, PID: 4942
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlite.so" not found
        at java.lang.Runtime.load0(Runtime.java:908)
        at java.lang.System.load(System.java:1505)
        at io.rong.imlib.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
        at io.rong.imlib.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:198)
        at io.rong.imlib.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at io.rong.imlib.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at io.rong.imlib.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at io.rong.imlib.NativeObject.<init>(NativeObject.java:17)
        at io.rong.imlib.NativeClient.init(NativeClient.java:195)
        at io.rong.imlib.LibHandlerStub.<init>(LibHandlerStub.java:44)
        at io.rong.imlib.ipc.RongService.onBind(RongService.java:35)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3218)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by leielyq** [comment]
加入so库解决
