### ISSUE TITLE
领取红包的时候出现崩溃

### ISSUE THREAD

**Issue by Dreamer206602** [sealtalk/sealtalk-android#21]
03-27 18:45:28.472 6871-8404/cn.rongcloud.im E/RongLog: [ RongExceptionHandler ] uncaughtException
                                                        java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                            at android.os.AsyncTask$3.done(AsyncTask.java:321)
                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                            at java.lang.Thread.run(Thread.java:833)
                                                         Caused by: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
                                                            at com.jrmf360.rylib.common.util.NetworkCacheUtil.downloadBitmapFromNet(Unknown Source)
                                                            at com.jrmf360.rylib.common.util.NetworkCacheUtil.access$000(Unknown Source)
                                                            at com.jrmf360.rylib.common.util.NetworkCacheUtil$BitmapTask.doInBackground(Unknown Source)
                                                            at com.jrmf360.rylib.common.util.NetworkCacheUtil$BitmapTask.doInBackground(Unknown Source)
                                                            at android.os.AsyncTask$2.call(AsyncTask.java:307)
                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246) 
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                            at java.lang.Thread.run(Thread.java:833) 
03-27 18:45:28.647 985-1004/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 52)
                                            
                                            --------- beginning of system

**Comment by Dreamer206602** [comment]
下载最新版的demo还是领取红包失败 测试手机是 华为P9Plus 和华为Nexus6P

**Comment by 13120241790** [comment]
现在这个问题应该在新版本做了修复
