### ISSUE TITLE
最新版本4.0.0.3 在启动页一直卡住无法进去

### ISSUE THREAD

**Issue by kulong51** [sealtalk/sealtalk-android#53]
rr: java.lang.IllegalStateException: Cannot invoke setValue on a background thread
W/System.err:     at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:462)
W/System.err:     at androidx.lifecycle.LiveData.setValue(LiveData.java:304)
W/System.err:     at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
W/System.err:     at com.ww.fewe.im.IMManager$1.onSuccess(IMManager.java:204)
 W/System.err:     at com.ww.fewe.im.IMManager$1.onSuccess(IMManager.java:201)
 W/System.err:     at com.ww.fewe.im.IMManager$18.onDatabaseOpened(IMManager.java:1380)
 W/System.err:     at io.rong.imkit.RongIM$3.onDatabaseOpened(RongIM.java:530)
 W/System.err:     at io.rong.imlib.RongIMClient$3.onDatabaseOpened(RongIMClient.java:724)
 W/System.err:     at io.rong.imlib.RongIMClient$5.OnDatabaseOpened(RongIMClient.java:877)
 W/System.err:   atio.rong.imlib.IConnectStringCallback$Stub.onTransact(IConnectStringCallback.java:87)

**Comment by kulong51** [comment]
> rr: java.lang.IllegalStateException: Cannot invoke setValue on a background thread
> W/System.err: at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:462)
> W/System.err: at androidx.lifecycle.LiveData.setValue(LiveData.java:304)
> W/System.err: at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
> W/System.err: at com.ww.fewe.im.IMManager$1.onSuccess(IMManager.java:204)
> W/System.err: at com.ww.fewe.im.IMManager$1.onSuccess(IMManager.java:201)
> W/System.err: at com.ww.fewe.im.IMManager$18.onDatabaseOpened(IMManager.java:1380)
> W/System.err: at io.rong.imkit.RongIM$3.onDatabaseOpened(RongIM.java:530)
> W/System.err: at io.rong.imlib.RongIMClient$3.onDatabaseOpened(RongIMClient.java:724)
> W/System.err: at io.rong.imlib.RongIMClient$5.OnDatabaseOpened(RongIMClient.java:877)
> W/System.err: atio.rong.imlib.IConnectStringCallback$Stub.onTransact(IConnectStringCallback.java:87)
